name: deploy

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main

# This job installs dependencies, build the jupyter notebook, and pushes it to a new `branch`
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up conda and dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
      # Install extra packages
      - name: Install jupyter dependencies
        run: |
          pip install jinja2==3.0.2
          pip install jupyter
          pip install nbconvert
      # Render the notebook
      - name: Render the notebook
        run: |
          jupyter nbconvert --to notebook --execute mynotebook.ipynb
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *nbconvert.ipynb
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
#      # Deploy rendered notebook to render branch
#      - name: Deploy to render branch
#        uses: peaceiris/actions-gh-pages@v3.6.1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: checklist_ro/_build/html
